version: "3"
services:
  app:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mybrary_db
  mybrary_db:
    image: mysql
    env_file:
      - db.env
    volumes:
      -  mybrary-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mybrary-data: